name: LETUS deadline watch

# ❶ 09:00 JST = 00:00 UTC に毎日実行
on:
  schedule:
    - cron:  '0 0 * * *'
  # 手動トリガも残しておくとデバッグしやすい
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest        # GitHub が用意した Ubuntu 仮想マシン
    steps:
      # ❷ ソースを取得
      - uses: actions/checkout@v4
       
      - name: Debug list files   # ← 追加
        run: ls -la
      # ❸ Python を用意（3.12 で OK）
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      # ❹ 依存パッケージと Playwright ブラウザをインストール
      - name: Install deps
        run: playwright install --with-deps chromium   # OS 依存ライブラリ込みで落とす

      # ❺ スクリプトを実行（静かなモード）
      - name: Run LETUS watcher
        env:
          LETUS_USERNAME: ${{ secrets.LETUS_USERNAME }}
          LETUS_PASSWORD: ${{ secrets.LETUS_PASSWORD }}
          LINE_NOTIFY_TOKEN: ${{ secrets.LINE_NOTIFY_TOKEN }}
        run: python letus_checker_secure.py --due-within 24 --quiet
